# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fluent-query}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Martin Kozák}]
  s.date = %q{2011-05-23}
  s.email = %q{martinkozak@martinkozak.net}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/fluent-query/compiler.rb",
    "lib/fluent-query/compilers/result.rb",
    "lib/fluent-query/connection.rb",
    "lib/fluent-query/data.rb",
    "lib/fluent-query/driver.rb",
    "lib/fluent-query/drivers/exception.rb",
    "lib/fluent-query/drivers/result.rb",
    "lib/fluent-query/exception.rb",
    "lib/fluent-query/queries/abstract.rb",
    "lib/fluent-query/queries/prepared.rb",
    "lib/fluent-query/queries/processor.rb",
    "lib/fluent-query/query.rb",
    "lib/fluent-query/result.rb",
    "lib/fluent-query/token.rb",
    "lib/fluent-query/tokens/raw.rb"
  ]
  s.homepage = %q{http://github.com/martinkozak/fluent-query}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.3}
  s.summary = %q{General way how to convert series of method calls to string query in an universal and system independent manner. This gem contains development libraries only. SQL implementation is available standalone.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hash-utils>, [">= 0.15.0"])
      s.add_runtime_dependency(%q<abstract>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<hashie>, [">= 1.0.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.13"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
    else
      s.add_dependency(%q<hash-utils>, [">= 0.15.0"])
      s.add_dependency(%q<abstract>, [">= 1.0.0"])
      s.add_dependency(%q<hashie>, [">= 1.0.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.13"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    end
  else
    s.add_dependency(%q<hash-utils>, [">= 0.15.0"])
    s.add_dependency(%q<abstract>, [">= 1.0.0"])
    s.add_dependency(%q<hashie>, [">= 1.0.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.13"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
  end
end

